"""add document classification columns

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 13:42:25.612762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('doc_type', sa.String(length=30), nullable=True))
    op.add_column('documents', sa.Column('doc_type_confidence', sa.Float(), nullable=True))
    op.add_column('documents', sa.Column('doc_type_scores', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('doc_type_corrected', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_column('documents', 'doc_type_corrected')
    op.drop_column('documents', 'doc_type_scores')
    op.drop_column('documents', 'doc_type_confidence')
    op.drop_column('documents', 'doc_type')
    # ### end Alembic commands ###
