"""add page classification columns

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-01 15:22:49.324185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_pages', sa.Column('doc_type', sa.String(length=30), nullable=True))
    op.add_column('document_pages', sa.Column('category', sa.String(length=20), nullable=True))
    op.add_column('document_pages', sa.Column('doc_type_confidence', sa.Float(), nullable=True))
    op.add_column('document_pages', sa.Column('doc_type_scores', sa.JSON(), nullable=True))
    op.add_column('document_pages', sa.Column('needs_review', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('document_pages', sa.Column('doc_type_reason', sa.String(length=200), nullable=True))
    op.add_column('document_pages', sa.Column('doc_type_corrected', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_document_pages_category'), 'document_pages', ['category'], unique=False)
    op.create_index(op.f('ix_document_pages_doc_type'), 'document_pages', ['doc_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_pages_doc_type'), table_name='document_pages')
    op.drop_index(op.f('ix_document_pages_category'), table_name='document_pages')
    op.drop_column('document_pages', 'doc_type_corrected')
    op.drop_column('document_pages', 'doc_type_reason')
    op.drop_column('document_pages', 'needs_review')
    op.drop_column('document_pages', 'doc_type_scores')
    op.drop_column('document_pages', 'doc_type_confidence')
    op.drop_column('document_pages', 'category')
    op.drop_column('document_pages', 'doc_type')
    # ### end Alembic commands ###
